---
- name: Create Keycloak configuration directory
  ansible.builtin.file:
    path: /opt/keycloak
    state: directory
    mode: '0755'

- name: Copy docker-compose template to Keycloak configuration directory
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /opt/keycloak/docker-compose.yaml
    mode: '0644'

- name: Start Keycloak using Docker Compose
  ansible.builtin.command: /usr/bin/docker compose -f /opt/keycloak/docker-compose.yaml up -d
  args:
    chdir: /opt/keycloak
  changed_when: false
